// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: notification/notification_service.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationStreamRequest) Reset() {
	*x = LocationStreamRequest{}
	mi := &file_notification_notification_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationStreamRequest) ProtoMessage() {}

func (x *LocationStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationStreamRequest.ProtoReflect.Descriptor instead.
func (*LocationStreamRequest) Descriptor() ([]byte, []int) {
	return file_notification_notification_service_proto_rawDescGZIP(), []int{0}
}

func (x *LocationStreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LocationStreamRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationStreamRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationStreamRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LocationStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationStreamResponse) Reset() {
	*x = LocationStreamResponse{}
	mi := &file_notification_notification_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationStreamResponse) ProtoMessage() {}

func (x *LocationStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_notification_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationStreamResponse.ProtoReflect.Descriptor instead.
func (*LocationStreamResponse) Descriptor() ([]byte, []int) {
	return file_notification_notification_service_proto_rawDescGZIP(), []int{1}
}

func (x *LocationStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_notification_notification_service_proto protoreflect.FileDescriptor

const file_notification_notification_service_proto_rawDesc = "" +
	"\n" +
	"'notification/notification_service.proto\x12\x14notification_service\"\x88\x01\n" +
	"\x15LocationStreamRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"2\n" +
	"\x16LocationStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x86\x01\n" +
	"\x13NotificationService\x12o\n" +
	"\x0eStreamLocation\x12+.notification_service.LocationStreamRequest\x1a,.notification_service.LocationStreamResponse(\x010\x01B\x0fZ\r/notificationb\x06proto3"

var (
	file_notification_notification_service_proto_rawDescOnce sync.Once
	file_notification_notification_service_proto_rawDescData []byte
)

func file_notification_notification_service_proto_rawDescGZIP() []byte {
	file_notification_notification_service_proto_rawDescOnce.Do(func() {
		file_notification_notification_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_notification_service_proto_rawDesc), len(file_notification_notification_service_proto_rawDesc)))
	})
	return file_notification_notification_service_proto_rawDescData
}

var file_notification_notification_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_notification_service_proto_goTypes = []any{
	(*LocationStreamRequest)(nil),  // 0: notification_service.LocationStreamRequest
	(*LocationStreamResponse)(nil), // 1: notification_service.LocationStreamResponse
}
var file_notification_notification_service_proto_depIdxs = []int32{
	0, // 0: notification_service.NotificationService.StreamLocation:input_type -> notification_service.LocationStreamRequest
	1, // 1: notification_service.NotificationService.StreamLocation:output_type -> notification_service.LocationStreamResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_notification_service_proto_init() }
func file_notification_notification_service_proto_init() {
	if File_notification_notification_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_notification_service_proto_rawDesc), len(file_notification_notification_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_notification_service_proto_goTypes,
		DependencyIndexes: file_notification_notification_service_proto_depIdxs,
		MessageInfos:      file_notification_notification_service_proto_msgTypes,
	}.Build()
	File_notification_notification_service_proto = out.File
	file_notification_notification_service_proto_goTypes = nil
	file_notification_notification_service_proto_depIdxs = nil
}
