// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: sos/sos_service.proto

package sos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSOSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSOSRequest) Reset() {
	*x = StartSOSRequest{}
	mi := &file_sos_sos_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSOSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSOSRequest) ProtoMessage() {}

func (x *StartSOSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sos_sos_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSOSRequest.ProtoReflect.Descriptor instead.
func (*StartSOSRequest) Descriptor() ([]byte, []int) {
	return file_sos_sos_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartSOSRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartSOSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartSOSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSOSResponse) Reset() {
	*x = StartSOSResponse{}
	mi := &file_sos_sos_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSOSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSOSResponse) ProtoMessage() {}

func (x *StartSOSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sos_sos_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSOSResponse.ProtoReflect.Descriptor instead.
func (*StartSOSResponse) Descriptor() ([]byte, []int) {
	return file_sos_sos_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartSOSResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_sos_sos_service_proto protoreflect.FileDescriptor

const file_sos_sos_service_proto_rawDesc = "" +
	"\n" +
	"\x15sos/sos_service.proto\x12\vsos_service\"D\n" +
	"\x0fStartSOSRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x10StartSOSResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2U\n" +
	"\n" +
	"SOSService\x12G\n" +
	"\bStartSOS\x12\x1c.sos_service.StartSOSRequest\x1a\x1d.sos_service.StartSOSResponseB\x06Z\x04/sosb\x06proto3"

var (
	file_sos_sos_service_proto_rawDescOnce sync.Once
	file_sos_sos_service_proto_rawDescData []byte
)

func file_sos_sos_service_proto_rawDescGZIP() []byte {
	file_sos_sos_service_proto_rawDescOnce.Do(func() {
		file_sos_sos_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sos_sos_service_proto_rawDesc), len(file_sos_sos_service_proto_rawDesc)))
	})
	return file_sos_sos_service_proto_rawDescData
}

var file_sos_sos_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sos_sos_service_proto_goTypes = []any{
	(*StartSOSRequest)(nil),  // 0: sos_service.StartSOSRequest
	(*StartSOSResponse)(nil), // 1: sos_service.StartSOSResponse
}
var file_sos_sos_service_proto_depIdxs = []int32{
	0, // 0: sos_service.SOSService.StartSOS:input_type -> sos_service.StartSOSRequest
	1, // 1: sos_service.SOSService.StartSOS:output_type -> sos_service.StartSOSResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sos_sos_service_proto_init() }
func file_sos_sos_service_proto_init() {
	if File_sos_sos_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sos_sos_service_proto_rawDesc), len(file_sos_sos_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sos_sos_service_proto_goTypes,
		DependencyIndexes: file_sos_sos_service_proto_depIdxs,
		MessageInfos:      file_sos_sos_service_proto_msgTypes,
	}.Build()
	File_sos_sos_service_proto = out.File
	file_sos_sos_service_proto_goTypes = nil
	file_sos_sos_service_proto_depIdxs = nil
}
