// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sos/sos_service.proto

package sos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SOSService_StartSOS_FullMethodName = "/sos_service.SOSService/StartSOS"
)

// SOSServiceClient is the client API for SOSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SOSServiceClient interface {
	StartSOS(ctx context.Context, in *StartSOSRequest, opts ...grpc.CallOption) (*StartSOSResponse, error)
}

type sOSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSOSServiceClient(cc grpc.ClientConnInterface) SOSServiceClient {
	return &sOSServiceClient{cc}
}

func (c *sOSServiceClient) StartSOS(ctx context.Context, in *StartSOSRequest, opts ...grpc.CallOption) (*StartSOSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSOSResponse)
	err := c.cc.Invoke(ctx, SOSService_StartSOS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SOSServiceServer is the server API for SOSService service.
// All implementations must embed UnimplementedSOSServiceServer
// for forward compatibility.
type SOSServiceServer interface {
	StartSOS(context.Context, *StartSOSRequest) (*StartSOSResponse, error)
	mustEmbedUnimplementedSOSServiceServer()
}

// UnimplementedSOSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSOSServiceServer struct{}

func (UnimplementedSOSServiceServer) StartSOS(context.Context, *StartSOSRequest) (*StartSOSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSOS not implemented")
}
func (UnimplementedSOSServiceServer) mustEmbedUnimplementedSOSServiceServer() {}
func (UnimplementedSOSServiceServer) testEmbeddedByValue()                    {}

// UnsafeSOSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SOSServiceServer will
// result in compilation errors.
type UnsafeSOSServiceServer interface {
	mustEmbedUnimplementedSOSServiceServer()
}

func RegisterSOSServiceServer(s grpc.ServiceRegistrar, srv SOSServiceServer) {
	// If the following call pancis, it indicates UnimplementedSOSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SOSService_ServiceDesc, srv)
}

func _SOSService_StartSOS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSOSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SOSServiceServer).StartSOS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SOSService_StartSOS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SOSServiceServer).StartSOS(ctx, req.(*StartSOSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SOSService_ServiceDesc is the grpc.ServiceDesc for SOSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SOSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sos_service.SOSService",
	HandlerType: (*SOSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSOS",
			Handler:    _SOSService_StartSOS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sos/sos_service.proto",
}
