FROM node:18 AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y protobuf-compiler

COPY package*.json ./
RUN npm install

COPY ../proto /proto

RUN npm run generate-proto

FROM node:18-slim

WORKDIR /app

COPY --from=builder /app .
COPY . .

CMD ["npm", "run", "dev"]